#!/bin/bash

set -x

set -eo pipefail

XDG_CONFIG_HOME=/tmp/.config
export XDG_CONFIG_HOME

export HOME=/opt/renderer

cd $HOME

URI_ROOT_PATH=/workshop
export URI_ROOT_PATH

if [ x"$JUPYTERHUB_SERVICE_PREFIX" != x"" ]; then
    URI_ROOT_PATH=${JUPYTERHUB_SERVICE_PREFIX%/}/workshop
fi

export PORT=10082

# Always recalculate the workshop directory in case running this due
# to it being restarted within the context of the container.

WORKSHOP_DIR=""

if [ -d /home/eduk8s/workshop ]; then
    WORKSHOP_DIR=/home/eduk8s/workshop
else
    if [ -d /opt/workshop ]; then
        WORKSHOP_DIR=/opt/workshop
    else
        if [ -d /opt/eduk8s/workshop ]; then
            WORKSHOP_DIR=/opt/eduk8s/workshop
        fi
    fi
fi

export WORKSHOP_DIR

# Start the workshop renderer.

exec npm start
