#!/bin/bash

set -eo pipefail

set -x

HTTPD_PORT=${HTTPD_PORT:-10084}

ARGS=""

ARGS="$ARGS --log-to-terminal"
ARGS="$ARGS --access-log"
ARGS="$ARGS --port $HTTPD_PORT"
ARGS="$ARGS --application-type static"
ARGS="$ARGS --embedded-mode"
ARGS="$ARGS --processes 1 --threads 5"

if [ x"$ENABLE_WEBDAV" == x"true" ]; then
    ARGS="$ARGS --include /opt/eduk8s/etc/httpd-webdav.conf"
fi

if [ x"$ENABLE_FILES" == x"true" ]; then
    FILES_ROOT=`workshop-definition -r "(.spec.session.applications.files.directory | select(type==\"string\"))"`
    if [ x"$FILES_ROOT" != x"" ]; then
        if [[ $FILES_ROOT != '/*'* ]]; then
            FILES_ROOT=/home/eduks8/$FILES_ROOT
        fi
    else
        FILES_ROOT=/home/eduk8s
    fi

    export FILES_ROOT

    ARGS="$ARGS --include /opt/eduk8s/etc/httpd-files.conf"
fi

cd /opt/httpd

source /opt/httpd/bin/activate

exec mod_wsgi-express start-server $ARGS
