#!/bin/bash

set -eo pipefail

set -x

URI_ROOT_PATH=/terminal
export URI_ROOT_PATH

if [ x"$JUPYTERHUB_SERVICE_PREFIX" != x"" ]; then
    URI_ROOT_PATH=${JUPYTERHUB_SERVICE_PREFIX%/}/terminal
fi

# Now execute the program. We need to supply a startup script for the
# shell to setup the environment.

MOTD_FILE=motd

if [ -f /opt/eduk8s/etc/motd ]; then
    MOTD_FILE=/opt/eduk8s/etc/motd
fi

if [ -f /opt/eduk8s/workshop/motd ]; then
    MOTD_FILE=/opt/eduk8s/workshop/motd
fi

if [ -f /home/eduk8s/workshop/motd ]; then
    MOTD_FILE=/home/eduk8s/workshop/motd
fi

cd /opt/butterfly

source /opt/butterfly/bin/activate

exec butterfly.server.py --port=10081 \
    --host=127.0.0.1 --uri-root-path="$URI_ROOT_PATH" --unsecure \
    --i-hereby-declare-i-dont-want-any-security-whatsoever \
    --shell=/opt/butterfly/start-terminal.sh --motd=$MOTD_FILE
