#!/bin/bash

set -x

DOWNLOAD_LOGFILE=/opt/assets/download-workshop.log
DOWNLOAD_FAILED=/opt/assets/download-workshop.failed

if [ -d /opt/assets ]; then
    if [ -f /opt/eduk8s/config/vendir-assets.yaml ]; then
        (vendir-workshop || touch $DOWNLOAD_FAILED) 2>&1 | tee -a $DOWNLOAD_LOGFILE
    fi
fi
