#!/bin/bash

set -x

OCTANT_ARGS=()

DEFAULT_NAMESPACE=${DEFAULT_NAMESPACE:-$SESSION_NAMESPACE}

OCTANT_VERSION=${OCTANT_VERSION:-$(workshop-definition -r '(.spec.session.applications.console.octant.version // "0.12.1")')}

if [ -f /var/run/secrets/kubernetes.io/serviceaccount/token ]; then
    OCTANT_ARGS+=("--namespace" "$DEFAULT_NAMESPACE")
fi

exec /opt/kubernetes/bin/octant@$OCTANT_VERSION --disable-open-browser \
    --listener-addr 127.0.0.1:10086 \
    --accepted-hosts console-$SESSION_NAMESPACE.$INGRESS_DOMAIN \
    "${OCTANT_ARGS[@]}"
