#!/bin/bash

set -eo pipefail

set -x

XDG_CONFIG_HOME=/tmp/.config
export XDG_CONFIG_HOME

TERMINAL_LAYOUT=${TERMINAL_LAYOUT=`workshop-definition -r '(.spec.session.applications.terminal.layout // "default")'`}
export TERMINAL_LAYOUT

cd /opt/gateway

NODE_PATH=`pwd`/node_modules
export NODE_PATH

exec node build/backend/server.js
