#!/bin/bash

set -eo pipefail
set -x

XDG_CONFIG_HOME=/tmp/.config
export XDG_CONFIG_HOME

WORKSHOP_LAYOUT=$(workshop-definition -r '(.spec.session.applications.workshop.layout // "default")')
export WORKSHOP_LAYOUT

TERMINAL_LAYOUT=$(workshop-definition -r '(.spec.session.applications.terminal.layout // "default")')
export TERMINAL_LAYOUT

EXERCISES_DIR=${EXERCISES_DIR:-exercises}

if [ -d $HOME/$EXERCISES_DIR ]; then
    TERMINAL_HOME=$HOME/$EXERCISES_DIR
fi

TERMINAL_HOME=${TERMINAL_HOME:-$HOME}

export TERMINAL_HOME

cd /opt/gateway

NODE_PATH=`pwd`/node_modules
export NODE_PATH

exec node build/backend/server.js
