#!/bin/bash

echo " -----> Running Django database migration"

if [ ! -f $WARPDRIVE_SRC_ROOT/db.sqlite3 ]; then
    THIS_IS_THE_FIRST_TIME=true
fi

python manage.py migrate

if [ x"$THIS_IS_THE_FIRST_TIME" = x"true" ]; then
    if [ x"$DJANGO_ADMIN_USERNAME" != x"" ]; then
        echo " -----> Creating predefined Django super user"
        (cat - | python manage.py shell) << !
from django.contrib.auth.models import User;
User.objects.create_superuser('$DJANGO_ADMIN_USERNAME',
                             '$DJANGO_ADMIN_EMAIL',
                             '$DJANGO_ADMIN_PASSWORD')
!
    else
        if (tty > /dev/null 2>&1); then
            echo " -----> Running Django super user creation"
            python manage.py createsuperuser
        fi
    fi
fi
