#!/bin/bash

echo " -----> Running Django database migration"

if [ ! -f $WARPDRIVE_SRC_ROOT/db.sqlite3 ]; then
    THIS_IS_THE_FIRST_TIME=true
fi

# Because we are swapping out the oauth2_provider.Application model, we
# need to run migrate once first without it swapped, in order to create
# the required database tables for the replacement. Then run a second
# migrate for good measure, although likely not required.

if [ x"$THIS_IS_THE_FIRST_TIME" = x"true" ]; then
    OAUTH2_PROVIDER_BOOTSTRAP=true python manage.py migrate
fi

python manage.py migrate

if [ x"$THIS_IS_THE_FIRST_TIME" = x"true" ]; then
    if [ x"$ADMIN_PASSWORD" != x"" ]; then
        echo " -----> Creating predefined Django super user"
        (cat - | python manage.py shell) << !
from django.contrib.auth.models import User;
User.objects.create_superuser('$ADMIN_USERNAME','$ADMIN_EMAIL','$ADMIN_PASSWORD')
!
    else
        if (tty > /dev/null 2>&1); then
            echo " -----> Running Django super user creation"
            python manage.py createsuperuser
        fi
    fi
fi
