#!/bin/bash

echo " -----> Running Django database migration"

if [ ! -f $WARPDRIVE_SRC_ROOT/db.sqlite3 ]; then
    THIS_IS_THE_FIRST_TIME=true
fi

python manage.py migrate

if [ x"$THIS_IS_THE_FIRST_TIME" = x"true" ]; then
    if [ x"$ADMIN_PASSWORD" != x"" ]; then
        echo " -----> Creating predefined Django super user"
        (cat - | python manage.py shell) << !
from django.contrib.auth.models import User
try:
    User.objects.get(username='$ADMIN_USERNAME')
except User.DoesNotExist:
    User.objects.create_superuser('$ADMIN_USERNAME','$ADMIN_EMAIL','$ADMIN_PASSWORD')
!
    else
        if (tty > /dev/null 2>&1); then
            echo " -----> Running Django super user creation"
            python manage.py createsuperuser
        fi
    fi
fi

if test -f /opt/app-root/config/theme.css; then
    cp /opt/app-root/config/theme.css /opt/app-root/src/static/workshops/css/theme.css
else
    touch /opt/app-root/src/static/workshops/css/theme.css
fi
