apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workshop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: workshop
