#!/usr/bin/python3

import os
import signal

# Restore the process signal handler for SIGPIPE otherwise the terminal will
# exit immediately. This is the main reason we are using a Python script here
# rather than a bash script.

signal.signal(signal.SIGPIPE, signal.SIG_DFL)

# Ensure we are in the required directory for the workshop as the dashboard
# process which spawns the terminal executes out of a different directory.

os.chdir(os.environ.get("TERMINAL_HOME", os.path.expanduser("~")))

# Setup arguments for executing the shell process as an interactive login shell
# so the system shell profile scripts are executed. If there is a command script
# for this specific named terminal session, delegate control to that instead of
# launching directly into the shell prompt.

args = ["terminal", "-il"]

session = os.environ.get("TERMINAL_SESSION_ID", "")

script_dirs = [
    "/home/eduk8s/workshop/terminal",
    "/opt/workshop/terminal",
    "/opt/eduk8s/workshop/terminal"
]

def is_executable(path):
    return os.path.isfile(path) and os.access(path, os.X_OK)

if session:
    for dir in script_dirs:
        if is_executable(f"{dir}/{session}.sh"):
            args.extend(["-c", f"{dir}/{session}.sh"])
            break

# Execute the shell process in place of this process.

os.execv("/bin/bash", args)
