# Generated by Django 3.0.3 on 2020-06-14 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workshops.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(default=0)),
                ('initial', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('inactivity', models.IntegerField(default=0)),
                ('tally', models.IntegerField(default=0)),
                ('resource', workshops.models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('vendor', models.CharField(max_length=128)),
                ('authors', workshops.models.JSONField(default=[])),
                ('difficulty', models.CharField(max_length=128)),
                ('duration', models.CharField(max_length=128)),
                ('tags', workshops.models.JSONField(default=[])),
                ('logo', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('content', workshops.models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=64)),
                ('state', models.IntegerField(choices=[(1, 'STARTING'), (2, 'RUNNING'), (3, 'STOPPED')], default=workshops.models.SessionState['STARTING'])),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=256, null=True)),
                ('redirect', models.URLField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshops.Environment')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='environment',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshops.Workshop'),
        ),
    ]
