# Generated by Django 3.0.3 on 2020-03-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
    ]
