# Generated by Django 3.0.3 on 2020-03-16 01:51

from django.db import migrations
import workshops.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_environment_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='resource',
            field=workshops.models.JSONField(default={}),
        ),
    ]
