#!/bin/sh

set -x

cd `dirname $0`/../src

TRAINING_PORTAL=portal-testing

REGISTRATION_TYPE=${REGISTRATION_TYPE:-anonymous}

OPERATOR_API_GROUP=educates.dev

OPERATOR_STATUS_KEY=educates
OPERATOR_NAME_PREFIX=educates

INGRESS_DOMAIN=${INGRESS_DOMAIN:-educates-local-dev.xyz}
INGRESS_PROTOCOL=${INGRESS_PROTOCOL:-http}

PORTAL_HOSTNAME=${PORTAL_HOSTNAME:-${TRAINING_PORTAL}-ui.${INGRESS_DOMAIN}:8080}

export OPERATOR_API_GROUP

export OPERATOR_STATUS_KEY
export OPERATOR_NAME_PREFIX

export TRAINING_PORTAL
export REGISTRATION_TYPE

export INGRESS_DOMAIN
export INGRESS_PROTOCOL

export PORTAL_HOSTNAME

python manage.py collectstatic --no-input

kubectl scale --replicas=0 deployment/training-portal -n ${TRAINING_PORTAL}-ui

exec ../bin/start-container
