#!/bin/sh

set -eo pipefail
set -x

cd `dirname $0`/..

TRAINING_PORTAL=portal-testing

PORTAL_UID=`kubectl get trainingportal/$TRAINING_PORTAL -o go-template='{{.metadata.uid}}'`

REGISTRATION_TYPE=${REGISTRATION_TYPE:-anonymous}

OPERATOR_API_GROUP=educates.dev

OPERATOR_STATUS_KEY=educates
OPERATOR_NAME_PREFIX=educates

INGRESS_DOMAIN=${INGRESS_DOMAIN:-educates-local-dev.test}
INGRESS_PROTOCOL=${INGRESS_PROTOCOL:-http}

PORTAL_HOSTNAME=${PORTAL_HOSTNAME:-${TRAINING_PORTAL}-ui.${INGRESS_DOMAIN}:8080}

export OPERATOR_API_GROUP

export OPERATOR_STATUS_KEY
export OPERATOR_NAME_PREFIX

export TRAINING_PORTAL
export PORTAL_UID

export REGISTRATION_TYPE

export INGRESS_DOMAIN
export INGRESS_PROTOCOL

export PORTAL_HOSTNAME

kubectl scale --replicas=0 deployment/training-portal -n ${TRAINING_PORTAL}-ui

kubectl delete workshopenvironments -l training.educates.dev/portal.name=$TRAINING_PORTAL --cascade=foreground

rm -f data/db.sqlite3 data/secret-key.txt

exec bin/start-container
