#!/bin/sh

set -x

cd `dirname $0`/../src

TRAINING_PORTAL=portal-testing

REGISTRATION_TYPE=${REGISTRATION_TYPE:-anonymous}

OPERATOR_API_GROUP=eduk8s.io

OPERATOR_STATUS_KEY=eduk8s
OPERATOR_NAME_PREFIX=eduk8s

INGRESS_DOMAIN=${INGRESS_DOMAIN:-training.eduk8s.io}
INGRESS_PROTOCOL=${INGRESS_PROTOCOL:-http}

PORTAL_HOSTNAME=${PORTAL_HOSTNAME:-${TRAINING_PORTAL}-ui.${INGRESS_DOMAIN}:8080}

export OPERATOR_API_GROUP

export OPERATOR_STATUS_KEY
export OPERATOR_NAME_PREFIX

export TRAINING_PORTAL
export REGISTRATION_TYPE

export INGRESS_DOMAIN
export INGRESS_PROTOCOL

export PORTAL_HOSTNAME

python manage.py collectstatic --no-input

kubectl scale --replicas=0 deployment/eduk8s-portal -n ${TRAINING_PORTAL}-ui

exec ../bin/start-container
