# Note: Set "rest-client.rememberCookiesForSubsequentRequests: false"

@rest_api_host=https://educates-cli-ui.educates-local-dev.test
@username=robot@educates
@password=my-pasword
@client_id=my-client-id
@client_secret=my-client-secret
@environment_name=educates-cli-w01
@index_url=https://www.example.com/

###

# @name catalog1
GET {{rest_api_host}}/workshops/catalog/environments

###

# @name login
POST {{rest_api_host}}/oauth2/token/
Authorization: Basic {{client_id}}:{{client_secret}}
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username={{username}}
&password={{password}}

###

# @name catalog2
GET {{rest_api_host}}/workshops/catalog/environments
Authorization: Bearer {{login.response.body.access_token}}

###

# @name catalog3
GET {{rest_api_host}}/workshops/catalog/environments?sessions=true
Authorization: Bearer {{login.response.body.access_token}}

###

# @name workshops1
GET {{rest_api_host}}/workshops/catalog/workshops
Authorization: Bearer {{login.response.body.access_token}}

###

# @name status1
GET {{rest_api_host}}/workshops/environment/{{environment_name}}/status/
Authorization: Bearer {{login.response.body.access_token}}

###

# @name status2
GET {{rest_api_host}}/workshops/environment/{{environment_name}}/status/?sessions=true
Authorization: Bearer {{login.response.body.access_token}}

###

# @name request1
POST {{rest_api_host}}/workshops/environment/{{environment_name}}/request/
    ?index_url={{index_url}}
    &email=grumpy@me.com
    &first_name=Grumpy
    &last_name=Old Man
    &timeout=300
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
    "parameters": [
        {
            "name": "WORKSHOP_USERNAME",
            "value": "VALUE1"
        }
    ]
}

###

# @name request2
GET {{rest_api_host}}/workshops/environment/{{environment_name}}/request/
    ?index_url={{index_url}}
    &user={{request1.response.body.user}}
Authorization: Bearer {{login.response.body.access_token}}

###

# @name session
GET {{rest_api_host}}{{request2.response.body.url}}

###

# @name config
GET {{rest_api_host}}/workshops/session/{{request1.response.body.name}}/config/
Authorization: Bearer {{login.response.body.access_token}}

###

# @name environment
GET {{config.response.body.url}}/config/environment?token={{config.response.body.password}}
Authorization: Bearer {{login.response.body.access_token}}

###

# @name variables
GET {{config.response.body.url}}/config/variables?token={{config.response.body.password}}
Authorization: Bearer {{login.response.body.access_token}}

###

# @name sessions
GET {{rest_api_host}}/workshops/user/{{request1.response.body.user}}/sessions/
Authorization: Bearer {{login.response.body.access_token}}

###

# @name catalog4
GET {{rest_api_host}}/workshops/catalog/environments?sessions=true
Authorization: Bearer {{login.response.body.access_token}}

###

# @name catalog5
GET {{rest_api_host}}/workshops/catalog/environments?sessions=true&state=running
Authorization: Bearer {{login.response.body.access_token}}

###

# @name catalog6
GET {{rest_api_host}}/workshops/catalog/environments?sessions=true&state=running&state=stopping
Authorization: Bearer {{login.response.body.access_token}}
