#@ load("@ytt:data", "data")

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: #@ "secretcopiers.secrets.{}".format(data.values.operator.apiGroup)
spec:
  scope: Cluster
  group: #@ "secrets.{}".format(data.values.operator.apiGroup)
  names:
    plural: secretcopiers
    singular: secretcopier
    kind: SecretCopier
    categories:
    - #@ "{}-secrets".format(data.values.operator.namePrefix)
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rules:
                  type: array
                  items:
                    type: object
                    required:
                    - sourceSecret
                    properties:
                      sourceSecret:
                        type: object
                        required:
                        - name
                        - namespace
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                      targetNamespaces:
                        type: object
                        properties:
                          nameSelector:
                            type: object
                            required:
                            - matchNames
                            properties:
                              matchNames:
                                type: array
                                items:
                                  type: string
                          uidSelector:
                            type: object
                            required:
                            - matchUIDs
                            properties:
                              matchUIDs:
                                type: array
                                items:
                                  type: string
                          ownerSelector:
                            type: object
                            required:
                            - matchOwners
                            properties:
                              matchOwners:
                                type: array
                                items:
                                  type: object
                                  required:
                                  - apiVersion
                                  - kind
                                  - name
                                  - uid
                                  properties:
                                    apiVersion:
                                      type: string
                                    kind:
                                      type: string
                                    name:
                                      type: string
                                    uid:
                                      type: string
                          labelSelector:
                            type: object
                            properties:
                              matchLabels:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                                additionalProperties:
                                  type: string
                              matchExpressions:
                                type: array
                                items:
                                  type: object
                                  required:
                                  - key
                                  - operator
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                      enum:
                                      - In
                                      - NotIn
                                      - Exists
                                      - DoesNotExist
                                    values:
                                      type: array
                                      items:
                                        type: string
                      targetSecret:
                        type: object
                        properties:
                          name:
                            type: string
                          labels:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            additionalProperties:
                              type: string
                      copyAuthorization:
                        type: object
                        properties:
                          sharedSecret:
                            type: string
                      reclaimPolicy:
                        type: string
                        enum:
                        - Delete
                        - Retain
                        default: Delete
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
