apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: systemprofiles.training.eduk8s.io
spec:
  scope: Cluster
  group: training.eduk8s.io
  names:
    plural: systemprofiles
    singular: systemprofile
    kind: SystemProfile
    categories:
    - eduk8s
    - eduk8s-training
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            ingress:
              type: object
              properties:
                domain:
                  type: string
                secret:
                  type: string
                class:
                  type: string
            storage:
              type: object
              properties:
                class:
                  type: string
                user:
                  type: integer
                group:
                  type: integer
            dockerd:
              type: object
              properties:
                mtu:
                  type: integer
            portal:
              type: object
              properties:
                image:
                  type: string
                credentials:
                  type: object
                  properties:
                    admin:
                      type: object
                      properties:
                        username:
                          type: string
                        password:
                          type: string
                    robot:
                      type: object
                      properties:
                        username:
                          type: string
                        password:
                          type: string
                clients:
                  type: object
                  properties:
                    robot:
                      type: object
                      properties:
                        id:
                          type: string
                        secret:
                          type: string
            environment:
              type: object
              properties:
                secrets:
                  type: object
                  properties:
                    pull:
                      type: array
                      items:
                        type: string
            workshop:
              type: object
              properties:
                images:
                  type: object
            registry:
              type: object
              properties:
                host:
                  type: string
                namespace:
                  type: string
                secret:
                  type: string
            analytics:
              type: object
              properties:
                google:
                  type: object
                  properties:
                    trackingId:
                      type: string
            theme:
              type: object
              properties:
                dashboard:
                  type: object
                  properties:
                    style:
                      type: string
                workshop:
                  type: object
                  properties:
                    style:
                      type: string
