#!/bin/bash

set -x

set -eo pipefail

for script in /opt/code-server/setup.d/*.sh; do
    if [ -x "$script" ]; then
        sh -x $script || true
    fi
done

for script in /opt/eduk8s/code-server/setup.d/*.sh; do
    if [ -x "$script" ]; then
        sh -x $script || true
    fi
done

for script in /opt/workshop/code-server/setup.d/*.sh; do
    if [ -x "$script" ]; then
        sh -x $script || true
    fi
done

for script in /home/eduk8s/workshop/code-server/setup.d/*.sh; do
    if [ -x "$script" ]; then
        sh -x $script || true
    fi
done

CODE_SERVER_BIND_ADDRESS=${CODE_SERVER_BIND_ADDRESS:-127.0.0.1}

EDITOR_HOME=${EDITOR_HOME:-/home/eduk8s}

exec /opt/code-server/bin/code-server \
    --bind-addr "$CODE_SERVER_BIND_ADDRESS:10085" \
    --auth none \
    --disable-update-check \
    --disable-telemetry \
    $EDITOR_HOME
