# Generated by Django 3.2.18 on 2023-04-14 01:38

from django.db import migrations, models
import project.apps.workshops.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='params',
            field=project.apps.workshops.models.JSONField(default={}, verbose_name='session params'),
        ),
        migrations.AddField(
            model_name='session',
            name='uid',
            field=models.CharField(default='', max_length=255, verbose_name='resource uid'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='params',
            field=project.apps.workshops.models.JSONField(default=[], verbose_name='session parameters'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(max_length=64, verbose_name='session id'),
        ),
    ]
