# Generated by Django 3.2.19 on 2023-05-13 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20230414_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='overdue',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='startup timeout'),
        ),
        migrations.AddField(
            model_name='trainingportal',
            name='default_overdue',
            field=models.CharField(default='', max_length=32, verbose_name='default overdue'),
        ),
    ]
