# Generated by Django 3.2.18 on 2023-04-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='uid',
            field=models.CharField(default='', max_length=255, verbose_name='resource uid'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(max_length=64, verbose_name='session id'),
        ),
    ]
