# Generated by Django 3.2.19 on 2023-06-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_auto_20230513_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='config password'),
        ),
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='activation token'),
        ),
    ]
