# Generated by Django 3.2.18 on 2023-04-12 03:39

from django.db import migrations
import project.apps.workshops.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_auto_20230412_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='inputs',
            field=project.apps.workshops.models.JSONField(default={}, verbose_name='session inputs'),
        ),
    ]
