# Generated by Django 3.2.20 on 2023-07-18 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_auto_20230628_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='refresh',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='refresh interval'),
        ),
        migrations.AddField(
            model_name='trainingportal',
            name='default_refresh',
            field=models.CharField(default='', max_length=32, verbose_name='default refresh'),
        ),
    ]
