# Generated by Django 3.2.20 on 2023-09-28 02:36

from django.db import migrations
import project.apps.workshops.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_remove_workshop_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='labels',
            field=project.apps.workshops.models.JSONField(default={}),
        ),
    ]
