# Generated by Django 4.2.8 on 2023-12-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0008_workshop_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingportal",
            name="generation",
            field=models.BigIntegerField(default=0, verbose_name="generation"),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="generation",
            field=models.BigIntegerField(verbose_name="generation"),
        ),
    ]
