# Generated by Django 4.2.8 on 2023-12-22 03:16

from django.db import migrations
import project.apps.workshops.models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0010_trainingportal_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingportal",
            name="labels",
            field=project.apps.workshops.models.JSONField(
                default={}, verbose_name="portal labels"
            ),
        ),
    ]
