# Generated by Django 4.2.8 on 2023-12-22 04:11

from django.db import migrations
import project.apps.workshops.models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0011_alter_trainingportal_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="labels",
            field=project.apps.workshops.models.JSONField(
                default={}, verbose_name="label overrides"
            ),
        ),
        migrations.AddField(
            model_name="trainingportal",
            name="default_labels",
            field=project.apps.workshops.models.JSONField(
                default={}, verbose_name="default labels"
            ),
        ),
    ]
