apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workshopsessions.training.eduk8s.io
spec:
  scope: Cluster
  group: training.eduk8s.io
  names:
    plural: workshopsessions
    singular: workshopsession
    kind: WorkshopSession
    categories:
    - eduk8s
    - eduk8s-training
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                environment:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string
                session:
                  type: object
                  required:
                  - id
                  properties:
                    id:
                      type: string
                    username:
                      type: string
                    password:
                      type: string
                    domain:
                      type: string
                    env:
                      type: array
                      items:
                        type: object
                        required:
                        - name
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                    ingress:
                      type: array
                      items:
                        type: object
                        required:
                        - name
                        properties:
                          name:
                            type: string
                          port:
                            type: integer
                request:
                  type: object
                  properties:
                    namespace:
                      type: string
                    kind:
                      type: string
                    apiVersion:
                      type: string
                    name:
                      type: string
                    uid:
                      type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                eduk8s:
                  type: object
                  properties:
                    url:
                      type: string
      additionalPrinterColumns:
      - name: URL
        type: string
        priority: 0
        description: The URL to access the workshop.
        jsonPath: .status.eduk8s.url
      - name: Username
        type: string
        priority: 0
        description: The username to access the workshop.
        jsonPath: .spec.session.username
      - name: Password
        type: string
        priority: 0
        description: The password to access the workshop.
        jsonPath: .spec.session.password
